token: vk1.a.k5JiGuNgdRn2ztm825Y24l4aji5wU_V4IfViy4zJNyw8BsSo2QC72b_aGflXyWyKWFUV-ls4gVPli5d2js-H9gvP4TZF7xDN54IcRTTO2pD-Rff0UJyz6bKninGzoOim38mPuFmaBo8ZpSGd1ZgRJncpQOUMNE4lpHoJqsxviG1wPwarFOgcqElrBcY3yP-D
confirmation_key: ff7eeb2f
port: 8080
redis_url: redis://127.0.0.1